### ISSUE TITLE
Add the possibility to overwrite redis-server configuration parameters

### ISSUE THREAD

**Issue by clamoriniere1A** [AmadeusITGroup/Redis-Operator#19]
Currently, only a few redis-server parameters can be set thru the `redis-node` parameters and `pod-template` present in the `Redis-Cluster` Custom-Resource.

The Idea is to add new Key-Value map field in the `Redis-Cluster.Spec` (like the `Metadata.Labels`) That will be used by the `redis-node` process to configure the Redis-Server process.

**Comment by gregbacchus** [comment]
Also it may be worth considering putting these into a `ConfigMap` that gets mounted into the container as a file, rather than having the `go` code modify the config file inside in the container. This would help take some of the responsibilities out of the container and into existing constructs within kubernetes.

**Comment by killmeplz** [comment]
https://github.com/AmadeusITGroup/Redis-Operator/pull/23
i'm not sure that i'm getting this right. But you can do that without any interventions into the code

**Comment by clamoriniere1A** [comment]
@killmeplz sure, but since the redis-node process is already playing with the configuration file, I didn't want to add another process (/bin/cp) in an init-container to do it.
in #22 PR I also to the time to re-organize the redis-node process parameter. and to support "read-only root file system" in containers.
