### ISSUE TITLE
Redisnode stopped working

### ISSUE THREAD

**Issue by killmeplz** [AmadeusITGroup/Redis-Operator#30]
```
docker run -it --entrypoint /bin/sh  redisoperator/redisnode:latest
/data # /redisnode 
/bin/sh: /redisnode: not found
```
After linking musl library everything works fine 

```
/data # mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
/data # /redisnode 
Program started at: 2018-10-01 16:51:49.758428273 +0000 UTC m=+0.221624727
```
Haven't found anything suspicious in recent commits.

**Comment by killmeplz** [comment]
BTW
It would be nice to have a docker image with version tag. For version locking

**Comment by clamoriniere1A** [comment]
@killmeplz thanks for reporting this issue,

today, I tried to release the version 0.1.1 (docker images and helm chart) https://github.com/AmadeusITGroup/Redis-Operator/releases/tag/0.1.1  in order to have like you say a docker image version locking. during the release process, the docker images were built with `goreleaser`, this introduces the bug... I rebuilt locally the docker image `redisoperator/redisnode:0.1.1` and `latest`.
It should again.

I keep open this issue, in order to track a proper fix for the release process.
